// Converts Natural Earth land-110m TopoJSON into a compact JS polygon file
// (equirectangular projection, normalized 0..1 coords, simplified).
const fs = require("fs");
const topojson = require("topojson-client");

const topo = JSON.parse(fs.readFileSync("node_modules/world-atlas/land-110m.json", "utf8"));
const geo = topojson.feature(topo, topo.objects.land);

const polys = [];
for (const feat of geo.features) {
  const geoms = feat.geometry.type === "Polygon" ? [feat.geometry.coordinates] : feat.geometry.coordinates;
  for (const rings of geoms) {
    const outer = rings[0]; // outer ring only; lakes not needed at this scale
    // equirectangular: x = (lon+180)/360, y = (90-lat)/180
    let pts = outer.map(([lon, lat]) => [(lon + 180) / 360, (90 - lat) / 180]);
    // light simplification: keep points at least ~0.004 apart (≈4px on a 1000px map)
    const kept = [pts[0]];
    for (const p of pts) {
      const q = kept[kept.length - 1];
      if (Math.hypot(p[0] - q[0], p[1] - q[1]) > 0.004) kept.push(p);
    }
    if (kept.length < 8) continue; // drop specks
    polys.push(kept.map(([x, y]) => [Math.round(x * 1000) / 1000, Math.round(y * 1000) / 1000]));
  }
}

const out =
  "/* Natural Earth 110m land polygons (public domain), equirectangular, normalized 0..1.\n" +
  "   Generated by tools/build-land.js — do not edit by hand. */\n" +
  "window.LAND_POLYGONS = " + JSON.stringify(polys) + ";\n";
fs.writeFileSync("land-data.js", out);

const points = polys.reduce((s, p) => s + p.length, 0);
console.log(`land-data.js written: ${polys.length} polygons, ${points} points, ${(out.length / 1024).toFixed(1)} KB`);
